import LocalizedStrings from 'react-native-localization';

const Strings = new LocalizedStrings({
    en: {
        "LANG": "en",
        "language": "english",
        "yes": "Yes",
        "cancel": "Cancel",
        "OK": "OK",
        "doYouWantToBuyThis": "Do You Want To Buy This ",
        "doYouWantToBuyThisFor": "Do You Want To Buy This For ",
        "play": "Play",
        "settings": "Settings",
        "coins": "Coins",
        "connectFailure": "Connection Failure Error",
        "sorryNoInternet": "Sorry No Internet Connection Detected!",
        "sorryTryAgain": "Sorry Please Try Again Later!",
        "sorryCantDisplay": "Sorry! This Page Can’t Be Displayed Right Now",
        "doYouWantToBuyLevelForBegin": "Do You Want To Buy This Level For",
        "doYouWantToBuyLevelForEnd": " Coins?",
        "noInAppPurchases": "InApp Purchases Are Disabled On Your Device",
        "accessPurchaseSuccessful": "Congratulations! Accessory purchase successful! Show Or Hide Using The Checkbox",
        "getCoins": "Get Coins",
        "levelAlreadyPurchased": "This Level Is Already Purchased",
        "congratsOnNewLevel": "Congratulations! Enjoy The New Level!",
        "level": "Level",
        "newLevels": "New Levels",
        "upgrade": "Upgrade",
        "price": "Price",
        "buy": "Buy",
        "accessory": "Accessory",
        "clickToSee": "Click to see",
        "get": "Get",
        "tryAllAccessories": "Try All Accessories",
        "selectGenre": "Select Genre",
        "selectLevel": "Select Level",
        "clickBayBayToHearHimSing": "Click BayBay to hear him sing!",
        "clickCorrectArtistRemoveByClicking": "Click the correct artist! Need Help? Remove 1 wrong answer by clicking \"?\".",
        "clickCorrectSongRemoveByClicking": "Click the correct song! Need help? Remove a wrong answer by clicking “?”",
        "sorryInsufficientCoinsBuyMore": "Sorry You Have Insufficient Coins, Would you Like to Buy More Coins? ",
        "yourBalanceIs": "Your Coin Balance is %d",
        "holdOnPleaseListenOnce": "Hold On Please Listen To The Clip At Least Once By Tapping On BayBay's Face! ",
        "removeOneWrongAnswer": "You can Remove 1 Wrong Answer for 100 Coins, Continue?",
        "congratsOnWinning200Coins": "Congratulations! You Have Won 200 Coins For Guessing The Right Answer On The First Try!",
        "sorryItunesLinkNotAvailable": "Sorry! iTunes Link Is Not Available",
        "goodGuess": "Good Guess!!",
        "backToLevel": "Back to Level",
        "strokeBaybayToStopCrying": "Stroke BayBay a few times to get him to stop crying!",
        "youreWrong": "You're Wrong",
        "tryAgain": "Try Again",
        "backToLevel2": "Back to Level",
        "sorryUnableToSendMail": "Sorry Unable To Send Mail! Please Configure At Least One Mail Account ",
        "instructions": "Instructions",
        "instructionsLine1": "Little BayBay loves music! So much so he hears his name everywhere.  Help BayBay figure out who’s calling his name!",
        "instructionsLine2": "To play the game, click PLAY, select a musical GENRE, LEVEL then choose game 1-16 from the grid.  ",
        "instructionsLine3": "Click BayBay's face to hear a short \"baby\" clip from a popular song.",
        "instructionsLine4": "Your goal is to select the correct artist and song title from the multiple choice options.  ",
        "instructionsLine5": "Get it right on the first try without any mistakes and increase BayBay’s musical coin collection by 200 coins! ",
        "instructionsLine6": "Unsure?  Click the \"?\" button to eliminate 1 wrong answer for 100 coins.",
        "instructionsLine7": "If you guess wrong, don’t worry, just tap BayBay a few times to calm him down then play again!",
        "instructionsLine8": "BayBay starts the game with 1,000 coins.  Use your coin collection to get new levels and even upgrade BayBay’s look.",
        "gameModes": "Game Modes",
        "instructionsLine9": "At the level grid screen, the check mark option on the slider  puts you in normal mode, play the game as usual. ",
        "instructionsLine10": "The note option on the slider puts you in soundboard mode.  Once you've solved a game, play with the BayBay sounds like a DJ! ",
        "instructionsLine11": "Login Facebook to save across your devices.",
        "haveFun": "Have fun with BayBay!!",
        "fullyLicensed": "All music fully licensed",
        "InfoEmail": "info@baybay.co"
    },
    fr: {
        "LANG": "fr",
        "language": "french",
        "yes": "Oui",
        "cancel": "Annuler",
        "OK": "D'accord",
        "doYouWantToBuyThis": "Voulez-vous acheter pour",
        "doYouWantToBuyThisFor": "Voulez-vous acheter pour ",
        "play": "Jouez",
        "settings": "Réglages",
        "coins": "Pièces",
        "connectFailure": "Défaut Erreur de connexion",
        "sorryNoInternet": "Désolé pas de connexion Internet détectée!",
        "sorryTryAgain": "Désolé S'il vous plaît réessayez plus tard!",
        "sorryCantDisplay": "Pardon! Cette page ne peut pas être affichée juste maintenant",
        "doYouWantToBuyLevelForBegin": "Voulez-vous acheter ce niveau pour",
        "doYouWantToBuyLevelForEnd": " pièces?",
        "noInAppPurchases": "Les achats en Application sont désactivés sur votre appareil",
        "accessPurchaseSuccessful": "Félicitations! Accessoire acheté avec succès! Afficher ou masquer en cochant la case",
        "getCoins": "Pièces",
        "levelAlreadyPurchased": "Ce niveau est déjà acquis",
        "congratsOnNewLevel": "Félicitations! Profitez du nouveau niveau!",
        "level": "Niveau",
        "newLevels": "Niveaux",
        "upgrade": "Accessoires",
        "price": "Prix",
        "buy": "Acheter",
        "accessory": "Accessoire",
        "clickToSee": "Cliquez pour voir",
        "get": "Obtenez",
        "tryAllAccessories": "Essayez Tous les accessoires",
        "selectGenre": "Sélectionnez Genre",
        "selectLevel": "Sélectionnez Niveau",
        "clickBayBayToHearHimSing": "Cliquez sur BayBay pour l'entendre chanter!",
        "clickCorrectArtistRemoveByClicking": "Cliquez sur l'artiste correct! Besoin d'aide? Retirer 1 mauvaise réponse en cliquant sur \"?\".",
        "clickCorrectSongRemoveByClicking": "Cliquez sur la chanson correcte! Besoin d'aide? Retirer une mauvaise réponse en cliquant sur \"?\"",
        "sorryInsufficientCoinsBuyMore": "Désolé Vous n’avez pas suffisamment de pièces, voulez-vous en acheter plus?",
        "yourBalanceIs": "Votre balance est de %d pièces",
        "holdOnPleaseListenOnce": "Attendez, s'il vous plaît écoutez le clip au moins une fois en appuyant sur le visage de BayBay!",
        "removeOneWrongAnswer": "Vous pouvez supprimer 1 réponse erronée pour 100 pièces, Continuer?",
        "congratsOnWinning200Coins": "Félicitations! Vous avez gagné 200 pièces pour deviner la bonne réponse à la première tentative!",
        "sorryItunesLinkNotAvailable": "Pardon!  Le lien iTunes ne semble pas disponible",
        "goodGuess": "Bien deviné!!",
        "backToLevel": "Retour à niveau",
        "strokeBaybayToStopCrying": "Caressez Baybay à quelques reprises pour qu’il arrête de pleurer!",
        "youreWrong": "Vous vous trompez",
        "tryAgain": "Réessayer",
        "backToLevel2": "Retour à niveau",
        "sorryUnableToSendMail": "Désolé Impossible d'envoyer du courrier! S'il vous plaît configurez au moins un compte de messagerie",
        "instructions": "Instructions",
        "instructionsLine1": "Petit Baybay aime la musique! Tant et si bien qu'il entend son nom partout. Aidez Baybay a savoir  qui appelle son nom!",
        "instructionsLine2": "Pour jouer au jeu, cliquez sur PLAY, sélectionner un GENRE musical, un NIVEAU puis choisissez le jeu 1-16 de la grille. ",
        "instructionsLine3": "Cliquez sur le visage de Baybay pour entendre un court extrait \"bébé\" d'une chanson populaire.",
        "instructionsLine4": "Votre but est de sélectionner l'artiste correct et le titre de la chanson parmi des options à choix multiples.",
        "instructionsLine5": "Ayez la reponse correcte des le premier essai sans aucune erreur et augmentez la collection de pièces de musique de Baybay de 200 pièces! ",
        "instructionsLine6": "Incertain? Cliquez le \"?\" bouton pour éliminer 1 mauvaise réponse pour 100 pièces.",
        "instructionsLine7": "Si vous n’avez pas la bonne reponse, ne vous inquiétez pas, il suffit de toucher Baybay à quelques reprises pour le calmer, puis jouez à nouveau!",
        "instructionsLine8": "Baybay commence le jeu avec 1000 pièces de monnaie. Utilisez votre collection de pièces pour obtenir de nouveaux niveaux et même améliorer l'apparence de Baybay.",
        "gameModes": "Modes de jeu",
        "instructionsLine9": "À l'écran de grille de niveau, l'option coche sur le curseur vous met en mode normal, jouer le jeu comme d'habitude.",
        "instructionsLine10": "L'option de note sur le curseur vous met en mode de table d'harmonie. Une fois que vous avez résolu un jeu, jouer avec les sons de Baybay comme un DJ!",
        "instructionsLine11": "Connectez-vous Facebook pour jouer sur tous vos appareils.",
        "haveFun": "Amusez-vous avec Baybay !!",
        "fullyLicensed": "Toutes musique entièrement sous licence",
        "InfoEmail": "info@baybay.co"
    },
    de: {
        "LANG": "de",
        "language": "german",
        "yes": "Ja",
        "cancel": "stornieren",
        "OK": "OK",
        "doYouWantToBuyThis": "Möchten Sie diesen für ",
        "doYouWantToBuyThisFor": "Möchten Sie diesen für ",
        "play": "Spielen",
        "settings": "Einstellungen",
        "coins": "Münzen",
        "connectFailure": "Verbindungsfehler",
        "sorryNoInternet": "Entschuldigung, es wurde keine Verbindung mit dem Internet gefunden!",
        "sorryTryAgain": "Entschuldigung, bitte versuchen Sie es später noch einmal",
        "sorryCantDisplay": "Entschuldigung! Diese Seite kann zur Zeit nicht angezeigt werden",
        "doYouWantToBuyLevelForBegin": "Möchten Sie diesen Level für ",
        "doYouWantToBuyLevelForEnd": " Münzen kaufen?",
        "noInAppPurchases": "InApp-Einkäufe sind bei ihrem Gerät deaktiviert",
        "accessPurchaseSuccessful": "Herzlichen Glückwunsch! Der Einkauf des Accessoires war erfolgreich! Zeige oder verstecke die Verwendung der Checkbox",
        "getCoins": "Bekommen Sie Münzen",
        "levelAlreadyPurchased": "Sie haben diesen Level bereits erworben",
        "congratsOnNewLevel": "Herzlichen Glückwunsch! Viel Spaß mit dem neuen Level!",
        "level": "Level",
        "newLevels": "Neue Levels",
        "upgrade": "Upgrade",
        "price": "Preis",
        "buy": "Kaufen",
        "accessory": "Accessoires",
        "clickToSee": "Klicken Sie hier um es zu sehen",
        "get": "Erhalten",
        "tryAllAccessories": "Testen Sie alle Accessoires",
        "selectGenre": "Wählen Sie das Genre",
        "selectLevel": "Wählen Sie den Level",
        "clickBayBayToHearHimSing": "Klicken Sie auf BayBay um ihn singen zu hören!",
        "clickCorrectArtistRemoveByClicking": "Klicken Sie auf den richtigen Künstler! Benötigen Sie Hilfe? Entfernen Sie die falsche Antwort in dem Sie \"?\" anklicken.",
        "clickCorrectSongRemoveByClicking": "Klicken Sie auf das richtige Lied! Benötigen Sie Hilfe? Entfernen Sie eine falsche Antwort in dem Sie \"?\" anklicken.",
        "sorryInsufficientCoinsBuyMore": "Entschuldigung Sie haben nicht genügend Münzen auf ihren Konto, möchten Sie Münzen erwerben? ",
        "yourBalanceIs": "Ihr Guthaben an Münzen beträgt %d",
        "holdOnPleaseListenOnce": "Warten Sie, bitte hören Sie sich den Clip wenigstens ein Mal an in dem Sie auf BayBays Gesicht klicken! ",
        "removeOneWrongAnswer": "Sie können eine falsche Antwort für 100 Münzen entfernen. Weiter?",
        "congratsOnWinning200Coins": "Herzlichen Glückwunsch! Sie haben durch das richtige Raten beim ersten Versuch 200 Münzen gewonnen!",
        "sorryItunesLinkNotAvailable": "Entschuldigung! iTunes Link steht nicht zur Verfügung",
        "goodGuess": "Viel Erfolg beim Raten",
        "backToLevel": "Zurück zum Level",
        "strokeBaybayToStopCrying": "Streicheln Sie BayBay ein paar mal damit er aufhört zu weinen!",
        "youreWrong": "Sie liegen falsch",
        "tryAgain": "Bitte versuchen Sie es noch einmal",
        "backToLevel2": "Zurück zum Level",
        "sorryUnableToSendMail": "Entschuldigung, die E-Mail kann nicht verschickt werden! Bitte stellen Sie mindestens einen E-Mail Account ein ",
        "instructions": "Anleitung",
        "instructionsLine1": "Der kleine BayBay liebt Musik! Und zwar so sehr dass er seinen Namen überall hört.  Helfen Sie BayBay herauszufinden wer seinen Namen ruft!",
        "instructionsLine2": "Um das Spiel zu spielen klicken Sie auf PLAY, wählen ein Musik-GENRE und dann den LEVEL des Spieles von 1-16 aus dem Gitter aus. ",
        "instructionsLine3": "Klicken Sie auf das Gesicht von BayBay um einen kurzen \"Baby\"-Clip vom einem beliebten Lied zu hören",
        "instructionsLine4": "Ihr Ziel ist es den richtigen Künstler und den richtigen Musiktitel aus den Multiple-Choice Optionen herauszufinden. ",
        "instructionsLine5": "Wenn Sie beim ersten Versuch richtig liegen und keinen Fehler machen dann erhöht sich das Münzguthaben von Baybay um 200 Münzen!  ",
        "instructionsLine6": "Unsicher?  Klicken Sie den \"?\"-Button um eine falsche Antwort für 100 Münzen zu löschen.",
        "instructionsLine7": "Wenn Sie falsch geraten haben, dann machen Sie sich keine Sorgen, streicheln Sie BayBay ain paar Mal um ihn zu beruhigen danach können Sie weiterspielen!",
        "instructionsLine8": "BayBay startet das Spiel mit 1000 Münzen.  Nutzen Sie ihr Guthaben an Münzen um neue Level zu erwerben, Sie können sogar BayBays Aussehen im Einstellungsmenü verbessern.",
        "gameModes": "Spiel-Modi",
        "instructionsLine9": "Bei der Anzeige des Level-Gitters, können Sie auf dem Slider die Option auswählen mit der Sie das Spiel im Normal-Modus spielen können. ",
        "instructionsLine10": "Die Noten-Option auf dem Slider versetzt Sie in den Soundboard-Modus. So bald Sie ein Spiel gelöst haben, können Sie mit den BayBay-Sounds wie ein DJ spielen! ",
        "instructionsLine11": "Login Facebook auf allen Geräten spielen.",
        "haveFun": "Viel Spaß mit BayBay!!",
        "fullyLicensed": "Alle Musikstücke sind vollständig lizenziert",
        "InfoEmail": "info@baybay.co"
    },
    it: {
        "LANG": "it",
        "language": "italian",
        "yes": "sì",
        "cancel": "Annulla",
        "OK": "OK",
        "doYouWantToBuyThis": "Vuoi Acquistare Questo Per ",
        "doYouWantToBuyThisFor": "Vuoi Acquistare Questo Per ",
        "play": "Giocare",
        "settings": "Impostazioni",
        "coins": "Monete",
        "connectFailure": "Errore Fallimento Connessione",
        "sorryNoInternet": "Mi dispiace Nessuna Connessione Internet Trovata!",
        "sorryTryAgain": "Mi Dispiace, Per Favore Riprova!",
        "sorryCantDisplay": "Mi Dispiace! Questa Pagina Non Può Essere Mostrata Adesso",
        "doYouWantToBuyLevelForBegin": "Vuoi Acquistare Questo Livello Per ",
        "doYouWantToBuyLevelForEnd": " Monete?",
        "noInAppPurchases": "Gli Acquisti InApp Sono Disabilitati Su Questo Apparecchio",
        "accessPurchaseSuccessful": "Congratulazioni! Acquisto accessori riuscito! Mostra O Nascondi Usando l'Elenco",
        "getCoins": "Ottieni Monete",
        "levelAlreadyPurchased": "Questo Livello E' Già Stato Acquistato",
        "congratsOnNewLevel": "Congratulazioni! Goditi Questo Nuovo Livello!",
        "level": "Livello",
        "newLevels": "Nuovi Livelli",
        "upgrade": "Upgrade",
        "price": "Prezzo",
        "buy": "Compra",
        "accessory": "Accessorio",
        "clickToSee": "Clicca per vedere",
        "get": "Ricevi",
        "tryAllAccessories": "Prova Tutti Gli Accessori",
        "selectGenre": "Seleziona Genere",
        "selectLevel": "Seleziona Livello",
        "clickBayBayToHearHimSing": "Clicca BayBay per ascoltarlo cantare!",
        "clickCorrectArtistRemoveByClicking": "Clicca sull'artista giusto! Bisogno d'aiuto? Rimuovi 1 risposta sbagliata cliccando \"?\".",
        "clickCorrectSongRemoveByClicking": "Clicca la canzone giusta! Bisogno d'aiuto? Rimuovi una risposta sbagliata cliccando “?”",
        "sorryInsufficientCoinsBuyMore": "Mi Dispiace Non Hai Abbastanza Monete, Vuoi Comprare Altre Monete? ",
        "yourBalanceIs": "L'Estratto Conto delle Tue Monete è %d",
        "holdOnPleaseListenOnce": "Per Favore Aspetta Ascolta il Clip Almeno Una Volta Cliccando sulla Faccia di BayBay! ",
        "removeOneWrongAnswer": "Puoi Rimuovere 1 Risposta Sbagliata per 100 Monete, Continuare?",
        "congratsOnWinning200Coins": "Congratulazioni! Hai Vinto 200 Monete Per Aver Indovinato La Risposta Esatta Al Primo Tentativo!",
        "sorryItunesLinkNotAvailable": "Mi Dispiace! Il Collegamento ad iTunes Non E' Disponibile",
        "goodGuess": "Risposta Giusta",
        "backToLevel": "Ritorno al Livello",
        "strokeBaybayToStopCrying": "Colpisci BayBay qualche volte per farlo smettere di piangere!",
        "youreWrong": "Hai Sbagliato",
        "tryAgain": "Riprova",
        "backToLevel2": "Ritorna al Livello",
        "sorryUnableToSendMail": "Mi Disipace Impossibile Inviare Mail! Per Favore Configura Almeno Un Account Di Posta ",
        "instructions": "Istruzioni",
        "instructionsLine1": "Little BayBay ama la musica! Talmente tanto che sente il suo nome dappertutto. Aiuta BayBay a capire chi stia facendo il suo nome!",
        "instructionsLine2": "Per giocare a questo gioco, clicca GIOCA, selezione un GENERE musicale, un LIVELLO poi scegli un gioco da 1 a 16 dalla griglia.  ",
        "instructionsLine3": "Clicca sulla faccia di BayBay per sentire un breve \"baby\" clip da una canzone conosciuta.",
        "instructionsLine4": "Il tuo scopo è di scegliere l'artista giusto ed il titolo della canzone dalle molteplici opzioni di scelta.  ",
        "instructionsLine5": "Fallo in modo giusto al primo tentativo senza errori ed aumenta la collezione di monete musicali di Bay di 200 monete!  ",
        "instructionsLine6": "Non sei sicuro?  Clicca il pulsante \"?\" per eliminare 1 risposta errata per 100 monete.",
        "instructionsLine7": "Se sbagli, non preoccuparti, clicca qualche volta su BayBay per calmarlo e poi gioca di nuovo!",
        "instructionsLine8": "BayBay inizia il gioco con 1,000 monete.  Usa le tue monete per raggiungere nuovi livelli e perfino aggiorna l'aspetto di  BayBay nel menu delle Impostazioni.",
        "gameModes": "Modalità di Gioco",
        "instructionsLine9": "A livello della griglia della schermata, l'opzione di smarcare sul cursore ti pone in modalità normale, gioca come al solito. ",
        "instructionsLine10": "L'opzione nota sul cursore ti pone in modalità tavola armonica.  Una volta che hai vinto il gioco, gioca coi suoni di BayBay come un DJ! ",
        "instructionsLine11": "Login Facebook a giocare su tutti i dispositivi.",
        "haveFun": "Divertiti con BayBay!!",
        "fullyLicensed": "Tutte le riproduzioni musicali completamente autorizzate",
        "InfoEmail": "info@baybay.co"
    },
    ar: {
        "LANG": "ar",
        "language": "arabic",
        "yes": "نعم فعلا",
        "cancel": "إلغاء",
        "OK": "حسنا",
        "doYouWantToBuyThis": "تريد هذه ل",
        "doYouWantToBuyThisFor": "تريد هذه ل ",
        "play": "اللعب",
        "settings": "الإعدادات",
        "coins": "العملات",
        "connectFailure": "خطاء بسبب  فشل الإتصال",
        "sorryNoInternet": "لم يتم إيجاد إتصال بشبكة الإنترنت ",
        "sorryTryAgain": "نعتذر , يرجى المحاولة لاحقاً ",
        "sorryCantDisplay": "نعتذر ! لا يمكن عرض هذه الصفحة حالياً ",
        "doYouWantToBuyLevelForBegin": "هل تريد شراء هذا المستوى مقابل ",
        "doYouWantToBuyLevelForEnd": " من العملات ؟",
        "noInAppPurchases": "مشتريات InApp  غير مفعلة في جهازك.",
        "accessPurchaseSuccessful": "مبارك ! تم شراء الاضافات بنجاح ! يمكنك إظهارها و إخفاءها بإستخدام صندوق الخيارات ",
        "getCoins": "الحصول على العملات",
        "levelAlreadyPurchased": "تم شراء هذا المستوى مسبقاً",
        "congratsOnNewLevel": "مبارك ! إستمتع بالمستوى الجديد !",
        "level": "مستوى",
        "newLevels": "مستويات جديدة",
        "upgrade": "تحديث",
        "price": "السعر ",
        "buy": "شراء ",
        "accessory": "إضافات",
        "clickToSee": "انقر للعرض ",
        "get": "الحصول عليها",
        "tryAllAccessories": "تجربة جميع الإضافات",
        "selectGenre": "قم بإختيار نوع الموسيقى  ",
        "selectLevel": "قم بإختيار المستوى ",
        "clickBayBayToHearHimSing": "انقر على BayBay لسماعه يغني !",
        "clickCorrectArtistRemoveByClicking": "انقر على المغني الصحيح ! هل تحتاج للمساعدة ؟ قم بإزالة الاجابة الخاطئة عن طرق نقر \"؟\" .",
        "clickCorrectSongRemoveByClicking": "انقر على الاغنية الصحيحة ! هل تحتاج للمساعدة ؟ قم بإزالة الاجابة الخاطئة عن طرق نقر \"؟\" .",
        "sorryInsufficientCoinsBuyMore": "نعتذر, انت لا تمتلك عدد كاف من العملات , هل تريد شراء المزيد منها ؟",
        "yourBalanceIs": "رصيد عملاتك هو %d",
        "holdOnPleaseListenOnce": "يرجى الإنتظار, قم بلإستماع الى المقطع على الاقل لمرة واحدة, من خلال مسح وجه BayBay",
        "removeOneWrongAnswer": "يمكنك إزالة إجابة خاطئة واحدة مقابل 100 من العملات , هل تريد الإستمرار ؟ ",
        "congratsOnWinning200Coins": "مبارك ! لقد حصلت على 200 عملة مقابل معرفة الاجابة الصحيحة من اول محاولة !",
        "sorryItunesLinkNotAvailable": "نعتذر ! ان رابط iTunes غير متاح حالياً",
        "goodGuess": "إجابة جيدة ",
        "backToLevel": "العودة الى المستوى ",
        "strokeBaybayToStopCrying": "قم بلمس BayBay عدة مرات ليتوقف عن البكاء ! ",
        "youreWrong": "إجابتك خاطئة ",
        "tryAgain": "حاول مرة اخرى ",
        "backToLevel2": "العودة الى المستوى",
        "sorryUnableToSendMail": "نعتذر , لا يمكن إرسال البريد الالكتروني في الوقت الراهن ! يرجى ضبط عنوان بريد الاكتروني واحد على الاقل .",
        "instructions": "التوجيهات ",
        "instructionsLine1": "BayBay الصغير يحب الموسيقى ! إنه يحب ان يسمع إسمه في كل مكان . ساعد BayBay ليعرف من ينادي بإسمه !",
        "instructionsLine2": "من اجل ان تجرب اللعبة , انقر على \"لعب\" , قم بإختيار نوع الموسيقى , المستوى , و من ثم إختر رقم ما بين 1 – 16 .",
        "instructionsLine3": " انقر على وجه BayBay لسماع مقطع صغير من اغنية معروفة جدا .",
        "instructionsLine4": "ان هدفك هو إختيار المغني الصحيح , و عنوان الاغنية من مجموعة خيارات .",
        "instructionsLine5": " احصل على الاجابة الصحيحة من اول محاولة ,  لزيادة عدد عملات BayBay الموسيقية بمقدار 200 عملة لكل اجابة صحيحة تتم من اول محاولة ! ",
        "instructionsLine6": "إذا كنت غير متأكد , فقط انقر على زر \"؟\" ليتم حذف اغنية واحدة مقابل 100 نقطة .",
        "instructionsLine7": "في حال اخطأت بالإجابة لا تقلق , فقط انقر على BayBay لعدة مرات حتى يهدىء و من ثم ابداء باللعب من جديدة , كما إنه بإمكانك ان ",
        "instructionsLine8": "تحسن من شكل و مظهر BayBay في قائمة الإعدادات .",
        "gameModes": "انماط اللعبة ",
        "instructionsLine9": "في الشاشة الخضراء الخاصة بالمستويات , رمز العلامة في الشريط , يضعك في النمط التقليدي , وتقوم بممارسة اللعبة كالمعتاد . ",
        "instructionsLine10": "ان خيار الملاحظة في الشريط , يضعك في نمط صندوق الاصوات . فور ان تحل اللعبة , سوف يصدر BayBay الاغاني مثل منسق الحفلات DJ ! ",
        "instructionsLine11": "تسجيل الدخول الفيسبوك للعب على جميع الأجهزة.",
        "haveFun": "إستمتع مع لعبة BayBay !",
        "fullyLicensed": "جميع المقاطع و الاغاني اصلية و مرخصة.",
        "InfoEmail": "info@baybay.co"
    },
    ja: {
        "LANG": "ja",
        "language": "japansese",
        "yes": "はい",
        "cancel": "キャンセル",
        "OK": "OK",
        "doYouWantToBuyThis": "あなたはこれが好きですか",
        "doYouWantToBuyThisFor": "あなたはこれが好きですか ",
        "play": "プレー",
        "settings": "設定",
        "coins": "コイン",
        "connectFailure": "接続失敗エラー",
        "sorryNoInternet": "すみません、インターネット接続が検出されませんでした！",
        "sorryTryAgain": "すみません、後で再び試みてください！",
        "sorryCantDisplay": "すみません！現在このページを表示できません",
        "doYouWantToBuyLevelForBegin": "こんにちは、",
        "doYouWantToBuyLevelForEnd": "つのコインでこのレベルを購入しますか？",
        "noInAppPurchases": "貴方のデバイスでは、InApp購入が無効になっています",
        "accessPurchaseSuccessful": "おめでとう！アクセサリーの購入に成功しました！チェックボックスを利用して表示または隠して下さい",
        "getCoins": "コインを購入",
        "levelAlreadyPurchased": "このレベルは、すでに購入しました",
        "congratsOnNewLevel": "おめでとう！新しいレベルを楽しんでください！",
        "level": "レベル",
        "newLevels": "新しいレベル",
        "upgrade": "アップグレード",
        "price": "価格",
        "buy": "購入",
        "accessory": "アクセサリー",
        "clickToSee": "クリックして見る",
        "get": "取得する",
        "tryAllAccessories": "全てのアクセサリーを試みる",
        "selectGenre": "ジャンルを選択",
        "selectLevel": "レベルを選択",
        "clickBayBayToHearHimSing": "BayBayの歌を聴くには、BayBayをクリックして下さい！",
        "clickCorrectArtistRemoveByClicking": "正確な芸術家をクリックして下さい！助けを必要としますか？“？”をクリックして間違った答えを除去してください。",
        "clickCorrectSongRemoveByClicking": "正確な歌をクリックして下さい！助けを必要としますか？“？”をクリックして間違った答えを除去してください。",
        "sorryInsufficientCoinsBuyMore": "すみません、貴方には十分なコインがありません。コインをもっと購入しますか？ ",
        "yourBalanceIs": "残っているコインは、%d つです",
        "holdOnPleaseListenOnce": "お待ちください、BayBayの顔をタップして、クリップを少なくとも1回聴いて下さい！ ",
        "removeOneWrongAnswer": "100 つのコインで１つの間違った答えを除去できます。続けますか？",
        "congratsOnWinning200Coins": "おめでとう！1回目の試みで正確な答えを当てたから、200つのコインを取りました！",
        "sorryItunesLinkNotAvailable": "すみません！iTunesリンクを利用できません",
        "goodGuess": "正しいです",
        "backToLevel": "レベルに戻る",
        "strokeBaybayToStopCrying": "BayBayを何回打って、泣き止むようにして下さい！",
        "youreWrong": "間違っています",
        "tryAgain": "もう一度試みて下さい",
        "backToLevel2": "レベルに戻る",
        "sorryUnableToSendMail": "すみません、メールを送信できません！少なくとも1つのメールアカウントを設定してください",
        "instructions": "使用説明書",
        "instructionsLine1": "小さいBayBayは、音楽を愛好しています！だからBayBayは、どこでも自分の名前をよく聞きます。誰がBayBayの名前を呼んでいるのかを知るようにBayBayを手伝って下さい！",
        "instructionsLine2": "ゲームをプレーするには、プレーをクリックして下さい。音楽ジャンルを選択すると、レベルがグリッドからゲーム1-16を選択します。",
        "instructionsLine3": "流行歌から短い“ベビー”クリップを聴くには、BayBayの顔をクリックして下さい。",
        "instructionsLine4": "貴方の目的は、多項選択オプションから正確な芸術家と曲名を選択することです。ンをクリックすると、100つのコインで1つの間違った答えを除去します。",
        "instructionsLine5": "1回目の試みで間違いなしに正確な答えを選択すると、BayBayの音楽コイン収集に200つのコインが増加されます！確信がありませんか？“？”ボタ",
        "instructionsLine6": "貴方の推測が間違っている場合は、BayBayを何回タップして落ち着けた後、再びゲームをプレーしてください！",
        "instructionsLine7": "貴方のコイン収集を利用して、新しいレベルを購入したり、設定メニューでBayBayの外観をアップグレードして下さい。",
        "instructionsLine8": "BayBayは、1000つのコインでゲームを始めます。",
        "gameModes": "ゲームモード",
        "instructionsLine9": "レベルグリッド画面で、スライダー上のチェックマークオプションを選択すると、通常モードになり、通常のとおりゲームをプレーします。",
        "instructionsLine10": "スライダー上のノートオプションを選択すると、サウンドボードモードになります。いったんゲームを解決すると、DJのように音を出すBayBayでプレーします！",
        "instructionsLine11": "Facebookにログインして、すべてのデバイスで再生します。",
        "haveFun": "BayBayで楽しく遊んでください！！",
        "fullyLicensed": "全ての音楽は、ライセンスを受けました",
        "InfoEmail": "info@baybay.co"
    },
    ko: {
        "LANG": "ko",
        "language": "korean",
        "yes": "예",
        "cancel": "취소",
        "OK": "승인",
        "doYouWantToBuyThis": "이걸 원해",
        "doYouWantToBuyThisFor": "이걸 원해 ",
        "play": "플레이",
        "settings": "설정",
        "coins": "코인",
        "connectFailure": "접속실패오유",
        "sorryNoInternet": "미안합니다, 인터네트접속이 검출되지않았습니다!",
        "sorryTryAgain": "미안합니다, 후에 다시 시도해주십시요!",
        "sorryCantDisplay": "미안합니다! 현재 이 페지를 표시할수 없습니다",
        "doYouWantToBuyLevelForBegin": "안녕하십니까, ",
        "doYouWantToBuyLevelForEnd": "개의 코인으로 이 레벨을 구입하겠습니까?",
        "noInAppPurchases": "당신의 장치에서는 InApp구입이 무효로 되여있습니다",
        "accessPurchaseSuccessful": "축하합니다! 악세서리의 구입에 성공하였습니다! 체크복스를 리용하여 표시 혹은 히든시켜주십시요",
        "getCoins": "코인을 구입",
        "levelAlreadyPurchased": "이 레벨은 이미 구입하였습니다",
        "congratsOnNewLevel": "축하합니다! 새로운 레벨을 즐겨주십시요!",
        "level": "수평",
        "newLevels": "새로운 레벨",
        "upgrade": "업그레이드",
        "price": "가격",
        "buy": "구입",
        "accessory": "악세서리",
        "clickToSee": "클릭하여 보기",
        "get": "얻기",
        "tryAllAccessories": "모든 악세서리를 시험해봅니다.",
        "selectGenre": "쟝르를 선택",
        "selectLevel": "레벨을 선택",
        "clickBayBayToHearHimSing": "BayBay의 노래를 들으려면 BayBay를 클릭해주십시요!",
        "clickCorrectArtistRemoveByClicking": "정확한 예술가를 클릭해주십시요! 도움이 필요됩니까? “?”를 클릭하여 틀린 대답을 제거해주십시요.",
        "clickCorrectSongRemoveByClicking": "정확한 노래를 클릭해주십시요! 도움이 필요됩니까? “?”를 클릭하여 틀린 대답을 제거해주십시요.",
        "sorryInsufficientCoinsBuyMore": "미안합니다, 당신에게는 충분한 코인이 없습니다. 코인을 좀더 구입하겠습니까? ",
        "yourBalanceIs": "남은 코인은 %d개입니다",
        "holdOnPleaseListenOnce": "기다려주십시요, BayBay의 얼굴을 탭하여 클립을 적어도 1번 들어주십시요! ",
        "removeOneWrongAnswer": "100개의 코인으로 1개의 틀린 대답을 제거할수 있습니다. 계속하겠습니까?",
        "congratsOnWinning200Coins": "축하합니다! 첫번째의 시도에서 정확한 답을 맞추었으므로 200개의 코인을 얻었습니다!",
        "sorryItunesLinkNotAvailable": "미안합니다! iTunes링크를 리용할수 없습니다",
        "goodGuess": "정확합니다",
        "backToLevel": "레벨로 돌아갑니다.",
        "strokeBaybayToStopCrying": "BayBay를 몇번 쳐서 울음을 그치게 해주십시요!",
        "youreWrong": "틀렸습니다",
        "tryAgain": "다시 한번 시도해주십시요",
        "backToLevel2": "레벨로 돌아갑니다.",
        "sorryUnableToSendMail": "미안합니다, 메일을 송신할수 없습니다! 적어도 1개의 메일계정을 설정해주십시요",
        "instructions": "사용설명서",
        "instructionsLine1": "작은 BayBay는 음악애호가입니다! 그래서 BayBay는 어디서나 자기의 이름을 자주 듣습니다. 누가 BayBay의 이름을 부르고있는가를 알수 있도록 BayBay를 도와주십시요!",
        "instructionsLine2": "게임을 플레이하려면 플레이를 클릭해주십시요. 음악쟝르를 선택하면 레벨이 그리드로부터 게임1-16을 선택합니다.",
        "instructionsLine3": "류행가에서 짧은 “베이비”클립을 들으려면 BayBay의 얼굴을 클릭해주십시요.",
        "instructionsLine4": "당신의 목적은 다항선택옵숀에서 정확한 예술가와 곡명을 선택하는것입니다.  ",
        "instructionsLine5": "첫번째의 시도로 틀림이 없이 정확한 답을 선택하면 BayBay의 음악코인수집에 200개의 코인이 증가됩니다!",
        "instructionsLine6": "믿어지지 않습니까? “?”단추를 클릭하면 100개의 코인으로 1개의 틀린 대답을 제거합니다.",
        "instructionsLine7": "당신의 추측이 틀린 경우는 BayBay를 몇번 탭하여 진정시킨후 다시 게임을 플레이해주십시요!",
        "instructionsLine8": "BayBay는 1000개의 코인으로 게임을 시작합니다. 당신의 코인수집을 리용하여 새로운 레벨을 구입하거나 설정메뉴에서 BayBay의 외형을 업그레이드해주십시요.",
        "gameModes": "게임모드",
        "instructionsLine9": "레벨그리드화면에서 슬라이드상의 체크마크옵숀을 선택하면 정상모드로 되며 보통때와 같이 게임을 플레이합니다.",
        "instructionsLine10": "슬라이드상의 노트옵숀을 선택하면 사운드보드모드로 됩니다. 일단 게임을 해결하면 DJ와 같이 소리를 내는 BayBay로 플레이합니다!",
        "instructionsLine11": "Facebook에 로그인하여 모든 기기에서 재생할 수 있습니다.",
        "haveFun": "BayBay로 즐거운 시간을 보내십시요！！",
        "fullyLicensed": "모든 음악은 라이센스를 받았습니다",
        "InfoEmail": "info@baybay.co"
    },
    pt: {
        "LANG": "pt",
        "language": "portugese",
        "yes": "sim",
        "cancel": "cancelar",
        "OK": "Está bem",
        "doYouWantToBuyThis": "Você gostaria de comprar isso para ",
        "doYouWantToBuyThisFor": "Você gostaria de comprar isso para ",
        "play": "Jogar",
        "settings": "Configurações",
        "coins": "Moedas",
        "connectFailure": "Erro: Falha na Conexão",
        "sorryNoInternet": "Desculpe, nenhuma conexão de internet detectada",
        "sorryTryAgain": "Desculpe, tente novamente mais tarde!",
        "sorryCantDisplay": "Esta página não pode ser exibida agora",
        "doYouWantToBuyLevelForBegin": "Você gostaria de comprar este nível por ",
        "doYouWantToBuyLevelForEnd": " moedas?",
        "noInAppPurchases": "Compras dentro do Aplicativo estão desabilitadas em seu aparelho",
        "accessPurchaseSuccessful": "Parabéns! Acessório comprador com sucesso! Mostre ou esconda usando a caixa de seleção",
        "getCoins": "Consiga Moedas",
        "levelAlreadyPurchased": "Este nível já foi comprado",
        "congratsOnNewLevel": "Parabéns! Aproveite o novo nível!",
        "level": "Nível",
        "newLevels": "Novos níveis",
        "upgrade": "Atualizar",
        "price": "Preço",
        "buy": "Comprar",
        "accessory": "Accssório",
        "clickToSee": "Clique para ver",
        "get": "Conseguir",
        "tryAllAccessories": "Experimentar todos os acessórios",
        "selectGenre": "Selecionar gênero",
        "selectLevel": "Selecionar nível",
        "clickBayBayToHearHimSing": "Clique em BayBay para ouví-lo cantar!",
        "clickCorrectArtistRemoveByClicking": "Clique no artista correto! Precisa de ajuda? Remova 1 resposta errada clicando em \"?\".",
        "clickCorrectSongRemoveByClicking": "Clique na música correta! Precisa de ajuda? Remova 1 resposta errada clicando em \"?\".",
        "sorryInsufficientCoinsBuyMore": "Desculpe, você não possui moedas suficientes, gostaria de comprar mais moedas? ",
        "yourBalanceIs": "Seu saldo de moedas é %d",
        "holdOnPleaseListenOnce": "Espere por favor, ouça o clip pelo menos uma vez clicando no Face de BayBay! ",
        "removeOneWrongAnswer": "Você pode remover 1 resposta errada por 100 moedas, continuar?",
        "congratsOnWinning200Coins": "Parabéns! Você ganhou 200 moedas por adivinhar a resposta certa na primeira tentativa!",
        "sorryItunesLinkNotAvailable": "Desculpe! O link do iTunes não está disponível",
        "goodGuess": "Bom Palpite",
        "backToLevel": "De volta ao nível",
        "strokeBaybayToStopCrying": "Acerte BayBay algumas vezes para fazê-lo parar de chorar!",
        "youreWrong": "Você está errado",
        "tryAgain": "Tente novamente",
        "backToLevel2": "De volta ao nível",
        "sorryUnableToSendMail": "Desculpe, impossibilitado de enviar mensagem! Por favor configure pelo menos uma conta de e-mail ",
        "instructions": "Instruções",
        "instructionsLine1": "O pequeno BayBay ama música! Tanto que ele ouve seu nome em todo lugar.  Ajude BayBay a descobrir quem o está chamando!",
        "instructionsLine2": "Para jogar, clique em JOGAR, selecione um gênero musical, NÍVEL então escolha o jogo de 1 a 16 da grade.  ",
        "instructionsLine3": "Clique no rosto de BayBay's face para ouvir um clip curto de uma música popular.",
        "instructionsLine4": "Seu objetivo é selecionar o artista certo e o título da música das opções de múltipla escolha.  ",
        "instructionsLine5": "Acerte logo na primeira tentative sem erros e aumente a coleção de moedas musicais de BayBay em 200 moedas!  ",
        "instructionsLine6": "Não tem certeza?  Clique no botão \"?\" para eliminar uma resposta errada por 100 moedas.",
        "instructionsLine7": "Se você errar, não se preocupe, apenas toque em BayBay algumas vezes para acalmá-lo, então jogue novamente!",
        "instructionsLine8": "BayBay começa o jogo com 1000 moedas.  Use sua coleção de moedas para conseguir novos níveis e até melhorar o visual de BayBay no meu COnfigurações.",
        "gameModes": "Modos de Jogo",
        "instructionsLine9": "Na tela de grade de níveis, a opção de marca de seleção na barra deslizante coloca você no modo normal, jogue como de costume. ",
        "instructionsLine10": "A opção de observação coloca você no modo placa de som.  Uma vez que você resolveu o jogo, brinque com os sons de BayBay como um DJ! ",
        "instructionsLine11": "Login Facebook para jogar em todos os dispositivos.",
        "haveFun": "Divirta-se com BayBay!!",
        "fullyLicensed": "Todas as músicas são totalmente autorizadas",
        "InfoEmail": "info@baybay.co"
    },
    ru: {
        "LANG": "ru",
        "language": "russian",
        "yes": "да",
        "cancel": "Отмена",
        "OK": "ОК",
        "doYouWantToBuyThis": "Вы хотите, чтобы купить это для",
        "doYouWantToBuyThisFor": "Вы хотите, чтобы купить это для ",
        "play": "Играть",
        "settings": "Настройки",
        "coins": "Монеты",
        "connectFailure": "Ошибка соединения",
        "sorryNoInternet": "Извините, подключение к Интернету отсутствует!",
        "sorryTryAgain": "Извините, попробуйте, пожалуйста, позже!",
        "sorryCantDisplay": "Извините! Сейчас эта страница не может быть отображена",
        "doYouWantToBuyLevelForBegin": "Вы хотели бы купить этот уровень за ",
        "doYouWantToBuyLevelForEnd": " монет?",
        "noInAppPurchases": "Покупки внутри приложения отключены на вашем устройстве",
        "accessPurchaseSuccessful": "Поздравляем! Вы приобрели аксессуар! Используйте флажок, чтобы показать или скрыть ",
        "getCoins": "Получить монеты",
        "levelAlreadyPurchased": "Вы уже купили этот уровень",
        "congratsOnNewLevel": "Поздравляем! Наслаждайтесь новым уровнем!",
        "level": "Уровень",
        "newLevels": "Новые уровни",
        "upgrade": "Улучшение",
        "price": "Цена",
        "buy": "Купить",
        "accessory": "Аксессуар",
        "clickToSee": "Нажмите для просмотра",
        "get": "Получить",
        "tryAllAccessories": "Попробовать все аксессуары",
        "selectGenre": "Выберите жанр",
        "selectLevel": "Выберите уровень",
        "clickBayBayToHearHimSing": "Нажмите на БэйБэй, чтобы услышать, как он поет!",
        "clickCorrectArtistRemoveByClicking": "Нажмите на правильного исполнителя! Нужна помощь? Уберите один неверный ответ, нажав \"?\".",
        "clickCorrectSongRemoveByClicking": "Нажмите на правильную песню! Нужна помощь? Уберите один неверный ответ, нажав “?”",
        "sorryInsufficientCoinsBuyMore": "Извините, у вас недостаточно монет. Вы хотели бы приобрести еще монеты? ",
        "yourBalanceIs": "Ваш баланс: %d монет",
        "holdOnPleaseListenOnce": "Не сдавайтесь! Пожалуйста, прослушайте отрывок из песни хотя бы раз, нажав на лицо БэйБэй!",
        "removeOneWrongAnswer": "Вы можете убрать один неверный ответ за 100 монет. Продолжить?",
        "congratsOnWinning200Coins": "Поздравляем! Вы выиграли 200 монет, угадав правильный ответ с первой попытки!",
        "sorryItunesLinkNotAvailable": "Извините! iTunes-ссылка недоступна",
        "goodGuess": "Вы угадали!",
        "backToLevel": "Назад на уровень",
        "strokeBaybayToStopCrying": "Погладьте БэйБэй несколько раз, чтобы он перестал плакать!",
        "youreWrong": "Вы ошиблись",
        "tryAgain": "Попробуйте снова",
        "backToLevel2": "Назад на уровень",
        "sorryUnableToSendMail": "Извините, невозможно отправить сообщение! Пожалуйста, настройте хотя бы одну учетную запись электронной почты",
        "instructions": "Инструкции",
        "instructionsLine1": "Крошка БэйБэй любит музыку! Так сильно, что он слышит свое имя везде.  Помогите БэйБэй выяснить, кто его зовет! ",
        "instructionsLine2": "Чтобы начать игру, нажмите ИГРАТЬ, выберите музыкальный ЖАНР, УРОВЕНЬ, затем выберите в таблице игру 1-16. ",
        "instructionsLine3": "Нажмите на лицо БэйБэй, чтобы прослушать короткий “детский” отрывок из популярной песни. ",
        "instructionsLine4": "Ваша цель – правильно выбрать исполнителя и название песни из нескольких вариантов ответов.",
        "instructionsLine5": "Отвечайте правильно с первой попытки и увеличивайте коллекцию музыкальных монет БэйБэй на 200 монет! ",
        "instructionsLine6": "Сомневаетесь? Нажмите кнопку “?”, чтобы убрать один неверный ответ за 100 монет. ",
        "instructionsLine7": "Если вы ответили неправильно – не расстраивайтесь, просто несколько раз нажмите на БэйБэй, чтобы успокоить его и продолжить игру!",
        "instructionsLine8": "БэйБэй начинает игру с 1 000 монет. Вы можете использовать монеты, чтобы открывать новые уровни и даже изменять внешность БэйБэй в меню Настройки.",
        "gameModes": "Режимы игры",
        "instructionsLine9": "На экране выбора уровня, передвиньте ползунок в сторону галочки, чтобы играть в обычном режиме.",
        "instructionsLine10": "А передвинув его в сторону значка с нотой, вы перейдете в режим диджейского пульта. Пройдя игру, вы сможете проигрывать мелодии БэйБэй как диджей!",
        "instructionsLine11": "Войдите в Facebook, чтобы играть на всех устройствах.",
        "haveFun": "Развлекайтесь с БэйБэй!!",
        "fullyLicensed": "Все музыкальные композиции полностью лицензированы",
        "InfoEmail": "info@baybay.co"
    },
    'zh-CN': {
        "LANG": "zh-CN",
        "language": "simplified chinese",
        "yes": "是",
        "cancel": "取消",
        "OK": "好",
        "doYouWantToBuyThis": "您想购买吗",
        "doYouWantToBuyThisFor": "您想购买吗 ",
        "play": "开始游戏",
        "settings": "设置",
        "coins": "金币",
        "connectFailure": "连接失败错误",
        "sorryNoInternet": "抱歉，未检测到网络连接！",
        "sorryTryAgain": "抱歉，请稍后再试！",
        "sorryCantDisplay": "抱歉！该页面现在无法显示！",
        "doYouWantToBuyLevelForBegin": "你想用",
        "doYouWantToBuyLevelForEnd": "金币购买该级别吗？",
        "noInAppPurchases": "你的设备禁用了应用内购买",
        "accessPurchaseSuccessful": "恭喜！附件购买成功！使用复选框进行显示或隐藏",
        "getCoins": "获得金币",
        "levelAlreadyPurchased": "已购买该级别",
        "congratsOnNewLevel": "恭喜！享受新级别吧！",
        "level": "水平",
        "newLevels": "新级别",
        "upgrade": "升级",
        "price": "价格",
        "buy": "购买",
        "accessory": "附件",
        "clickToSee": "点击查看",
        "get": "获取",
        "tryAllAccessories": "试用所有附件",
        "selectGenre": "选择流派",
        "selectLevel": "选择级别",
        "clickBayBayToHearHimSing": "点击BayBay听他唱歌！",
        "clickCorrectArtistRemoveByClicking": "点击正确的艺术家！需要帮助？点击“？”去掉一个错误答案。",
        "clickCorrectSongRemoveByClicking": "点击正确的歌曲！需要帮助？点击“？”去掉一个错误答案。",
        "sorryInsufficientCoinsBuyMore": "抱歉，你的金币不足，想购买更多金币吗？",
        "yourBalanceIs": "你的金币余额是%d",
        "holdOnPleaseListenOnce": "请稍候，轻击BayBay的脸部至少听一遍片段！",
        "removeOneWrongAnswer": "你可以用100金币去掉一个错误答案，继续吗？",
        "congratsOnWinning200Coins": "恭喜！你首次尝试猜对了正确答案，赢得了200枚金币！",
        "sorryItunesLinkNotAvailable": "抱歉，iTunes链接不可用",
        "goodGuess": "猜得好",
        "backToLevel": "返回级别",
        "strokeBaybayToStopCrying": "抚摸BayBay几下让他停止哭泣！",
        "youreWrong": "你答错了",
        "tryAgain": "重试",
        "backToLevel2": "返回级别",
        "sorryUnableToSendMail": "抱歉，无法发送邮件！请至少设置一个邮件账户",
        "instructions": "说明",
        "instructionsLine1": "小Baybay热爱音乐！以至于他到处都听到他的名字。帮助BayBay找出是谁在叫他的名字！",
        "instructionsLine2": "要开始玩游戏，请点击开始游戏，选择音乐流派、级别，然后从网格中选择游戏1-16。",
        "instructionsLine3": "点击BayBay的脸部，就可以听到某首流行歌曲中的一小段“baby”片段。",
        "instructionsLine4": "你的目标是从多个选项中选择正确的艺术家和歌曲名称。",
        "instructionsLine5": "首次尝试正确无误的话， BayBay的音乐金币收藏会增加200金币！",
        "instructionsLine6": "如果不确定，可以点击“?”按钮，用100金币去掉一个错误答案。",
        "instructionsLine7": "如果你猜错了，不要担心，只需轻击BayBay几次，让他平静下来，然后再开始游戏！",
        "instructionsLine8": "BayBay游戏的初始金币为1000枚。利用你的金币收集到达新级别，甚至可以在设置目录中升级BayBay的外观。",
        "gameModes": "游戏模式",
        "instructionsLine9": "在级别网格屏幕上，滑块上的复选标记为正常模式选项，像往常一样玩游戏。",
        "instructionsLine10": "滑块上的音符为音板模式选项。在答完一局后，和听起来就像是一个DJ 的BayBay一起玩！",
        "instructionsLine11": "登录Facebook以在所有设备上播放。",
        "haveFun": " 和BayBay一起共度快乐时光！",
        "fullyLicensed": " 所有音乐均拥有完全授权",
        "InfoEmail": "info@baybay.co"
    },
    es: {
        "LANG": "es",
        "language": "spanish",
        "yes": "sí",
        "cancel": "cancelar",
        "OK": "DE ACUERDO",
        "doYouWantToBuyThis": "¿Quieres comprar este por ",
        "doYouWantToBuyThisFor": "¿Quieres comprar este por ",
        "play": "Jugar",
        "settings": "Ajustes",
        "coins": "Monedas",
        "connectFailure": "Error - Falla de conexión",
        "sorryNoInternet": "Lo sentimos ¡No se detecta conexión a Internet!",
        "sorryTryAgain": "Lo sentimos ¡Por favor inténtalo de nuevo más tarde!",
        "sorryCantDisplay": "¡Lo sentimos! Esta página no se puede mostrar ahora",
        "doYouWantToBuyLevelForBegin": "¿Quieres comprar este nivel por ",
        "doYouWantToBuyLevelForEnd": " monedas?",
        "noInAppPurchases": "Las compras InApp están desactivadas en su dispositivo",
        "accessPurchaseSuccessful": "¡Felicitaciones! ¡Compra de accesorio exitosa! Muéstralo u ocúltalo marcando la casilla",
        "getCoins": "Conseguir monedas",
        "levelAlreadyPurchased": "Este nivel ya ha sido comprado",
        "congratsOnNewLevel": "¡Felicitaciones! ¡Disfruta el nivel nuevo! ",
        "level": "Nivel",
        "newLevels": "Niveles nuevos",
        "upgrade": "Actualizar // Ascender",
        "price": "Precio",
        "buy": "Comprar",
        "accessory": "Accesorio",
        "clickToSee": "Clic para ver",
        "get": "Obtener",
        "tryAllAccessories": "Prueba todos los accesorios",
        "selectGenre": "Selecciona genero",
        "selectLevel": "Selecciona nivel",
        "clickBayBayToHearHimSing": "¡Haz clic en BayBay para escucharlo cantar!",
        "clickCorrectArtistRemoveByClicking": "¡Haz clic en el artista correcto! ¿Necesitas ayuda? Elimina 1 respuesta incorrecta hacienda clic en \"?\".",
        "clickCorrectSongRemoveByClicking": "¡Haz clic en la canción correcta! ¿Necesitas ayuda? Elimina 1 respuesta incorrecta hacienda clic en \"?\"",
        "sorryInsufficientCoinsBuyMore": "Lo sentimos, no tienes suficientes monedas. ¿Quieres comprar más monedas? ",
        "yourBalanceIs": "Tu saldo de monedas es %d",
        "holdOnPleaseListenOnce": "Espera por favor. ¡Escucha el clip al menos una vez tocando en la cara de BayBay! ",
        "removeOneWrongAnswer": "Puedes eliminar 1 respuesta incorrecta por 100 monedas. ¿Deseas continuar? ",
        "congratsOnWinning200Coins": "¡Felicitaciones! ¡Haz ganado 200 monedas por adivinar la respuesta correcta en el primer intento!",
        "sorryItunesLinkNotAvailable": "¡Lo sentimos! iTunes no está disponible",
        "goodGuess": "Buena conjetura",
        "backToLevel": "Volver al nivel",
        "strokeBaybayToStopCrying": "¡Golpea a BayBay un par de veces para que deje de llorar!",
        "youreWrong": "Estas equivocado",
        "tryAgain": "Intenta de nuevo",
        "backToLevel2": "Volver al nivel",
        "sorryUnableToSendMail": "Lo sentimos, ¡Imposible enviar el correo! Por favor configura al menos una cuenta de correo",
        "instructions": "Instrucciones",
        "instructionsLine1": "¡El pequeño BayBay ama la música! Le gusta tanto, que oye su nombre por todas partes. ¡Ayuda a BayBay a descubrir quién lo está llamando!",
        "instructionsLine2": "Para empezar el juego haz clic en JUGAR, selecciona un GÉNERO musical, un NIVEL y a continuación elije un juego de 1-16. ",
        "instructionsLine3": "Haz clic en la cara BayBay para escuchar un corto \"baby\" clip de una canción popular.",
        "instructionsLine4": "Tu objetivo es seleccionar correctamente el artista y el título de la canción entre las múltiples alternativas. ",
        "instructionsLine5": "¡Selecciona la respuesta correcta en el primer intento y aumenta la colección de monedas musicales de BayBay en 200 monedas!",
        "instructionsLine6": "¿No estás seguro de tu respuesta? Haz clic en el botón \"?\" para eliminar 1 respuesta incorrecta usando 100 monedas.",
        "instructionsLine7": "Si tu respuesta es incorrecta, no te preocupes, simplemente pulsa a BayBay un par de veces para calmarlo  y luego ¡Podrás jugar de nuevo!",
        "instructionsLine8": "BayBay empieza el juego con 1.000 monedas. Utiliza su colección de monedas para conseguir nuevos niveles y para mejorar el aspecto de BayBay en el menú de Configuración.",
        "gameModes": "Modos de juego",
        "instructionsLine9": "En la pantalla de niveles, la casilla de verificación en el control deslizante ajusta el juego en modo normal, así puedes jugar como de costumbre.",
        "instructionsLine10": "La opción de nota sobre el deslizador, ajusta el juego en modo soundboard. De esta manera una vez que hayas pasado el juego, ¡podrás jugar con los sonidos de BayBay como un DJ!",
        "instructionsLine11": "Inicie sesión en Facebook para jugar en todos los dispositivos.",
        "haveFun": "¡Diviertete con BayBay!",
        "fullyLicensed": "Toda la música cuenta con completa licencia",
        "InfoEmail": "info@baybay.co"
    },
    'zh-HK': {
        "LANG": "zh-HK",
        "language": "traditional chinese",
        "yes": "是",
        "cancel": "取消",
        "OK": "好",
        "doYouWantToBuyThis": "您想購買嗎",
        "doYouWantToBuyThisFor": "您想購買嗎 ",
        "play": "開始遊戲",
        "settings": "設置",
        "coins": "金幣",
        "connectFailure": "連接失敗錯誤",
        "sorryNoInternet": "抱歉，未檢測到網路連接！",
        "sorryTryAgain": "抱歉，請稍後再試！",
        "sorryCantDisplay": "抱歉！該頁面現在無法顯示！",
        "doYouWantToBuyLevelForBegin": "你想用",
        "doYouWantToBuyLevelForEnd": "金幣購買該級別嗎？",
        "noInAppPurchases": "你的設備禁用了應用內購買",
        "accessPurchaseSuccessful": "恭喜！附件購買成功！使用核取方塊進行顯示或隱藏",
        "getCoins": "獲得金幣",
        "levelAlreadyPurchased": "已購買該級別",
        "congratsOnNewLevel": "恭喜！享受新級別吧！",
        "level": "水平",
        "newLevels": "新級別",
        "upgrade": "升級",
        "price": "價格",
        "buy": "購買",
        "accessory": "附件",
        "clickToSee": "點擊查看",
        "get": "獲取",
        "tryAllAccessories": "試用所有附件",
        "selectGenre": "選擇流派",
        "selectLevel": "選擇級別",
        "clickBayBayToHearHimSing": "點擊BayBay聽他唱歌！",
        "clickCorrectArtistRemoveByClicking": "點擊正確的藝術家！需要幫助？點擊“？”去掉一個錯誤答案。",
        "clickCorrectSongRemoveByClicking": "點擊正確的歌曲！需要幫助？點擊“？”去掉一個錯誤答案。",
        "sorryInsufficientCoinsBuyMore": "抱歉，你的金幣不足，想購買更多金幣嗎？",
        "yourBalanceIs": "你的金幣餘額是%d",
        "holdOnPleaseListenOnce": "請稍候，輕擊BayBay的臉部至少聽一遍片段！",
        "removeOneWrongAnswer": "你可以用100金幣去掉一個錯誤答案，繼續嗎？",
        "congratsOnWinning200Coins": "恭喜！你首次嘗試猜對了正確答案，贏得了200枚金幣！",
        "sorryItunesLinkNotAvailable": "抱歉，iTunes連結不可用",
        "goodGuess": "猜得好",
        "backToLevel": "返回級別",
        "strokeBaybayToStopCrying": "撫摸BayBay幾下讓他停止哭泣！",
        "youreWrong": "你答錯了",
        "tryAgain": "重試",
        "backToLevel2": "返回級別",
        "sorryUnableToSendMail": "抱歉，無法發送郵件！請至少設置一個郵件帳戶",
        "instructions": "說明",
        "instructionsLine1": "小Baybay熱愛音樂！以至於他到處都聽到他的名字。幫助BayBay找出是誰在叫他的名字！",
        "instructionsLine2": "要開始玩遊戲，請點擊開始遊戲，選擇音樂流派、級別，然後從網格中選擇遊戲1-16。",
        "instructionsLine3": "點擊BayBay的臉部，就可以聽到某首流行歌曲中的一小段“baby”片段。",
        "instructionsLine4": "你的目標是從多個選項中選擇正確的藝術家和歌曲名稱。",
        "instructionsLine5": "首次嘗試正確無誤的話， BayBay的音樂金幣收藏會增加200金幣！",
        "instructionsLine6": "如果不確定，可以點擊“?”按鈕，用100金幣去掉一個錯誤答案。",
        "instructionsLine7": "如果你猜錯了，不要擔心，只需輕擊BayBay幾次，讓他平靜下來，然後再開始遊戲！",
        "instructionsLine8": "BayBay遊戲的初始金幣為1000枚。利用你的金幣收集到達新級別，甚至可以在設置目錄中升級BayBay的外觀。",
        "gameModes": "遊戲模式",
        "instructionsLine9": "在級別網格螢幕上，滑塊上的核取記號為正常模式選項，像往常一樣玩遊戲。",
        "instructionsLine10": "滑塊上的音符為音板模式選項。在答完一局後，和聽起來就像是一個DJ 的BayBay一起玩！",
        "instructionsLine11": "登錄Facebook以在所有設備上播放。",
        "haveFun": " 和BayBay一起共度快樂時光！",
        "fullyLicensed": "所有音樂均擁有完全授權",
        "InfoEmail": "info@baybay.co"
    },
    'zh-TW': {
        "LANG": "zh-TW",
        "language": "traditional chinese",
        "yes": "是",
        "cancel": "取消",
        "OK": "好",
        "doYouWantToBuyThis": "您想購買嗎",
        "doYouWantToBuyThisFor": "您想購買嗎 ",
        "play": "開始遊戲",
        "settings": "設置",
        "coins": "金幣",
        "connectFailure": "連接失敗錯誤",
        "sorryNoInternet": "抱歉，未檢測到網路連接！",
        "sorryTryAgain": "抱歉，請稍後再試！",
        "sorryCantDisplay": "抱歉！該頁面現在無法顯示！",
        "doYouWantToBuyLevelForBegin": "你想用",
        "doYouWantToBuyLevelForEnd": "金幣購買該級別嗎？",
        "noInAppPurchases": "你的設備禁用了應用內購買",
        "accessPurchaseSuccessful": "恭喜！附件購買成功！使用核取方塊進行顯示或隱藏",
        "getCoins": "獲得金幣",
        "levelAlreadyPurchased": "已購買該級別",
        "congratsOnNewLevel": "恭喜！享受新級別吧！",
        "level": "水平",
        "newLevels": "新級別",
        "upgrade": "升級",
        "price": "價格",
        "buy": "購買",
        "accessory": "附件",
        "clickToSee": "點擊查看",
        "get": "獲取",
        "tryAllAccessories": "試用所有附件",
        "selectGenre": "選擇流派",
        "selectLevel": "選擇級別",
        "clickBayBayToHearHimSing": "點擊BayBay聽他唱歌！",
        "clickCorrectArtistRemoveByClicking": "點擊正確的藝術家！需要幫助？點擊“？”去掉一個錯誤答案。",
        "clickCorrectSongRemoveByClicking": "點擊正確的歌曲！需要幫助？點擊“？”去掉一個錯誤答案。",
        "sorryInsufficientCoinsBuyMore": "抱歉，你的金幣不足，想購買更多金幣嗎？",
        "yourBalanceIs": "你的金幣餘額是%d",
        "holdOnPleaseListenOnce": "請稍候，輕擊BayBay的臉部至少聽一遍片段！",
        "removeOneWrongAnswer": "你可以用100金幣去掉一個錯誤答案，繼續嗎？",
        "congratsOnWinning200Coins": "恭喜！你首次嘗試猜對了正確答案，贏得了200枚金幣！",
        "sorryItunesLinkNotAvailable": "抱歉，iTunes連結不可用",
        "goodGuess": "猜得好",
        "backToLevel": "返回級別",
        "strokeBaybayToStopCrying": "撫摸BayBay幾下讓他停止哭泣！",
        "youreWrong": "你答錯了",
        "tryAgain": "重試",
        "backToLevel2": "返回級別",
        "sorryUnableToSendMail": "抱歉，無法發送郵件！請至少設置一個郵件帳戶",
        "instructions": "說明",
        "instructionsLine1": "小Baybay熱愛音樂！以至於他到處都聽到他的名字。幫助BayBay找出是誰在叫他的名字！",
        "instructionsLine2": "要開始玩遊戲，請點擊開始遊戲，選擇音樂流派、級別，然後從網格中選擇遊戲1-16。",
        "instructionsLine3": "點擊BayBay的臉部，就可以聽到某首流行歌曲中的一小段“baby”片段。",
        "instructionsLine4": "你的目標是從多個選項中選擇正確的藝術家和歌曲名稱。",
        "instructionsLine5": "首次嘗試正確無誤的話， BayBay的音樂金幣收藏會增加200金幣！",
        "instructionsLine6": "如果不確定，可以點擊“?”按鈕，用100金幣去掉一個錯誤答案。",
        "instructionsLine7": "如果你猜錯了，不要擔心，只需輕擊BayBay幾次，讓他平靜下來，然後再開始遊戲！",
        "instructionsLine8": "BayBay遊戲的初始金幣為1000枚。利用你的金幣收集到達新級別，甚至可以在設置目錄中升級BayBay的外觀。",
        "gameModes": "遊戲模式",
        "instructionsLine9": "在級別網格螢幕上，滑塊上的核取記號為正常模式選項，像往常一樣玩遊戲。",
        "instructionsLine10": "滑塊上的音符為音板模式選項。在答完一局後，和聽起來就像是一個DJ 的BayBay一起玩！",
        "instructionsLine11": "登錄Facebook以在所有設備上播放。",
        "haveFun": " 和BayBay一起共度快樂時光！",
        "fullyLicensed": "所有音樂均擁有完全授權",
        "InfoEmail": "info@baybay.co"
    },
    tr: {
        "LANG": "tr",
        "language": "turkish",
        "yes": "Evet",
        "cancel": "iptal etmek",
        "OK": "tamam",
        "doYouWantToBuyThis": "Için satın almak ister misin",
        "doYouWantToBuyThisFor": "Için satın almak ister misin ",
        "play": "Oyna",
        "settings": "Ayarlar",
        "coins": "Coinler",
        "connectFailure": "Başarısız Bağlantı Hatası ",
        "sorryNoInternet": "Üzgünüz İnternet Bağlantısı Saptanmadı! ",
        "sorryTryAgain": "Üzgünüz Lütfen Sonra Tekrar Deneyin! ",
        "sorryCantDisplay": "Üzgünüz! Bu Sayfa Şu Anda Görüntülenemiyor",
        "doYouWantToBuyLevelForBegin": "Bu Seviyeyi ",
        "doYouWantToBuyLevelForEnd": " Coin Karşılığında Satın Almak İster misiniz? ",
        "noInAppPurchases": "Cihazınızda Uygulama İçi Satın Almalar Devre Dışı ",
        "accessPurchaseSuccessful": "Tebrikler! Aksesuar satın alımı başarılı! İşaret Kutucuğunu Kullanarak Gösterin ya da Gizleyin ",
        "getCoins": "Coin Al",
        "levelAlreadyPurchased": "Bu Seviye Zaten Satın Alındı ",
        "congratsOnNewLevel": "Tebrikler! Yeni Seviyenin Keyfini Çıkarın! ",
        "level": "Seviye",
        "newLevels": "Yeni Seviyeler ",
        "upgrade": "Yükselt ",
        "price": "Fiyat",
        "buy": "Satın Al",
        "accessory": "Aksesuar",
        "clickToSee": "Görmek için tıklayın ",
        "get": "Al",
        "tryAllAccessories": "Bütün Aksesuarları Dene",
        "selectGenre": "Tür Seç",
        "selectLevel": "Seviye Seç",
        "clickBayBayToHearHimSing": "Şarkı söylemesini duymak için BayBay’i tıklayın! ",
        "clickCorrectArtistRemoveByClicking": "Doğru sanatçıyı tıklayın! Yardıma mı ihtiyacınız var? \"?\" üzerine tıklayarak bir yanlış cevabı kaldırın.  ",
        "clickCorrectSongRemoveByClicking": "Doğru şarkıyı tıklayın! Yardıma mı ihtiyacınız var? \"?\" üzerine tıklayarak bir yanlış cevabı kaldırın.  ",
        "sorryInsufficientCoinsBuyMore": "Üzgünüz Yeterli Coininiz Yok, Daha Fazla Coin Satın Almak İster misiniz? ",
        "yourBalanceIs": "Coin Bakiyeniz %d",
        "holdOnPleaseListenOnce": "Lütfen Bekleyin BayBay ‘ın Yüzüne Hafifçe Vurarak Klibi En Az Bir Kere Dinleyin! ",
        "removeOneWrongAnswer": "100  Coin Karşılığında 1 Yanlış Cevabı Kaldırabilirsiniz, Devam Etmek İster misiniz? ",
        "congratsOnWinning200Coins": "Tebrikler! İlk Denemede Doğru Cevabı Tahmin Ettiğiniz İçin 200 Coin Kazandınız! ",
        "sorryItunesLinkNotAvailable": "Üzgünüz! iTunes Linki Mevcut Değil! ",
        "goodGuess": "İyi Tahmin",
        "backToLevel": "Seviyeye Geri Dön ",
        "strokeBaybayToStopCrying": "Ağlamasını durdurmak için BayBay’a birkaç kere vurun! ",
        "youreWrong": "Hatalısınız",
        "tryAgain": "Tekrar deneyin",
        "backToLevel2": "Seviyeye Geri Dön",
        "sorryUnableToSendMail": "Üzgünüz E-Posta Gönderilemedi! Lütfen En Az Bir E-Posta Hesabı Yapılandırın! ",
        "instructions": "Talimatlar",
        "instructionsLine1": "Minik BayBay müziği sever! O kadar çok ki kendi adını her yerde duyar. BayBay’e onu kimi çağırdığını anlamasında yardım edin! ",
        "instructionsLine2": "Oyunu oynamak için OYNA’ya tıklayın, bir müzik TÜRÜ ve SEVİYE seçin daha sonra da grid sisteminden 1-16 arasından oyun seçin. ",
        "instructionsLine3": "Popüler bir şarkının kısa bir “baby” klibini dinlemek için BayBay’in yüzüne tıklayın. ",
        "instructionsLine4": "Hedefiniz çoktan seçmeli seçenekler arasından doğru sanatçı ve şarkı adını seçmek.",
        "instructionsLine5": "İlk denemede hiç hata yapmadan doğruyu bilin ve BayBay’in müzik coin koleksiyonunu 200 coine yükseltin! ",
        "instructionsLine6": "Emin değil misniz? 1 yanlış cevabı elemek için 100 coin karşılığında \"?\" butonuna tıklayın.",
        "instructionsLine7": "Eğer yanlış tahminde bulunursanız üzülmeyin, onu sakinleştirmek için sadece BayBay’a birkaç kere hafifçe vurun ve sonra tekrar oynayın!",
        "instructionsLine8": "BayBay oyunu 1,000 coin ile başlatır. Yeni seviyeler almak için coin koleksiyonunuzu kullanın ve Ayarlar menüsünden BayBay’in görünümünü bile değiştirin.",
        "gameModes": "Oyun Modları",
        "instructionsLine9": "Seviye grid ekranında, kaydırıcıdaki onay işareti sizi normal moda geçirir, oyunu her zamanki gibi oynarsınız.",
        "instructionsLine10": "Kaydırıcıdaki nota seçeneği sizi soundboard moduna geçirir. Bir oyunu çözdüğünüz zaman, BayBay ile oyun DJ’lik yapmak gibidir!",
        "instructionsLine11": "Cihazlar arasında kaydetmek için Facebook'a giriş yapın.",
        "haveFun": "BayBay ile iyi eğlenceler!! ",
        "fullyLicensed": "Tüm müzikler tamamen lisanslıdır. ",
        "InfoEmail": "info@baybay.co"
    }
});

export default Strings;
